Repository KSPModdingLibs/KSPCommunityFixes, pull requests merged in 2025-03, with the labels that each got.

#264 Fix for #236 : Improved ModuleIndexingMismatch patch
  KSPCommunityFixes/BugFixes/ModuleIndexingMismatch.cs
  README.md
Labels: kspModding

#269 Loading optimizations
  GameData/KSPCommunityFixes/Settings.cfg
  KSPCommunityFixes/BasePatch.cs
  KSPCommunityFixes/KSPCommunityFixes.cs
  KSPCommunityFixes/KSPCommunityFixes.csproj
  KSPCommunityFixes/Library/MuParser.cs
  KSPCommunityFixes/Library/ShaderHelpers.cs
  KSPCommunityFixes/Library/StaticHelpers.cs
  KSPCommunityFixes/Performance/FastLoader.cs
  KSPCommunityFixes/Performance/GameDatabasePerf.cs
  KSPCommunityFixes/Performance/MinorPerfTweaks.cs
  KSPCommunityFixes/Performance/PartParsingPerf.cs
Labels: kspPerformance

#270 Faster implementation of `TemperatureGaugeSystem`
  KSPCommunityFixes/Performance/PartSystemsFastUpdate.cs
Labels: kspPerformance

#278 New modding patch : BaseFieldListUseFieldHost
  GameData/KSPCommunityFixes/Settings.cfg
  KSPCommunityFixes/KSPCommunityFixes.csproj
  KSPCommunityFixes/Modding/BaseFieldListUseFieldHost.cs
Labels: kspModding

#299 More balanced CommNetThrottling performance patch
  GameData/KSPCommunityFixes/Settings.cfg
  KSPCommunityFixes/Performance/CommNetThrottling.cs
  README.md
Labels: kspPerformance

#285 Allow targeting the currently orbited parent body, or any body the parent body is a descendant of
  GameData/KSPCommunityFixes/Settings.cfg
  KSPCommunityFixes/KSPCommunityFixes.csproj
  KSPCommunityFixes/QoL/TargetParentBody.cs
  README.md
Labels: kspQoL

#281 Optimise VectorLine camera projection for improved Map View performance
  GameData/KSPCommunityFixes/Settings.cfg
  KSPCommunityFixes/KSPCommunityFixes.cs
  KSPCommunityFixes/KSPCommunityFixes.csproj
  KSPCommunityFixes/Library/Numerics.cs
  KSPCommunityFixes/Performance/OptimisedVectorLines.cs
  README.md
Labels: kspPerformance

#284 Reduce Craft Browser Open and Search Times
  GameData/KSPCommunityFixes/Settings.cfg
  KSPCommunityFixes/KSPCommunityFixes.csproj
  KSPCommunityFixes/Performance/CraftBrowserOptimisations.cs
  README.md
Labels: kspPerformance
